### ISSUE TITLE
doc jobs are failing on some executors

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/buildfarm#214]
This one is failing: http://jenkins.ros.org/job/doc-indigo-darwin_control/4/console 

Whereas this one passes: http://jenkins.ros.org/job/doc-indigo-darwin_control/2/console

Builds 1 and 3 replecate the issues. 

Reading the logs it appears that they have different bootstrap images, with the failing jobs always on the same machine and using liquidweb's mirrors. 

I'm going to pull the doc tag from that executor: http://jenkins.ros.org/computer/64.91.254.177_sync/

It is the oldest one since it stays around as the sync machine. There must be some old state in the system. Possibly an old image, that needs a dist-upgrade before installation will work? 

```
Installing ros and genmsg
Executing command 'apt-get install ros-indigo-ros ros-indigo-genmsg --yes'
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-indigo-ros : Depends: ros-indigo-mk but it is not going to be installed
                  Depends: ros-indigo-rosbuild but it is not going to be installed
                  Depends: ros-indigo-roslib but it is not going to be installed
                  Depends: ros-indigo-rosunit but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
/!\  Failed to execute command '['apt-get', 'install', 'ros-indigo-ros', 'ros-indigo-genmsg', '--yes']' with return code 100
Traceback (most recent call last):
  File "/home/rosbuild/hudson/workspace/doc-indigo-darwin_control/jenkins_scripts/doc", line 221, in <module>
    main()
  File "/home/rosbuild/hudson/workspace/doc-indigo-darwin_control/jenkins_scripts/doc", line 119, in main
    doit(args.rosdistro, args.repo, workspace, docspace, args.platform, args.arch, args.no_chroot, args.skip_garbage, args.force)
  File "/home/rosbuild/hudson/workspace/doc-indigo-darwin_control/jenkins_scripts/doc", line 184, in doit
    call("apt-get install ros-%s-ros ros-%s-genmsg --yes" % (install_distro, install_distro))
  File "/home/rosbuild/hudson/workspace/doc-indigo-darwin_control/jenkins_scripts/common.py", line 148, in call
    return call_with_list(command.split(' '), envir=envir, verbose=verbose, return_output=return_output)
  File "/home/rosbuild/hudson/workspace/doc-indigo-darwin_control/jenkins_scripts/common.py", line 142, in call_with_list
    raise BuildException(msg)
common.BuildException
```

Re: https://github.com/ros/rosdistro/pull/7349#issuecomment-76675986

**Comment by tfoote** [comment]
I disabled doc tag on that machine. It's treating the symptom, but with the new buildfarm on the way I don't think it's worth root causing this issue.

**Comment by tfoote** [comment]
This same machine appears to be failing devel jobs too. http://jenkins.ros.org/job/devel-indigo-turtlebot/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/20/console

**Comment by tfoote** [comment]
The one difference I could find in the logs is that this machine was using liquidweb caches, the newer machines don't have that so I think liquidweb stopped providing them, and they're probably missing some of the required updates for the newer packages. 

```
Working on distro indigo and repo/stack darwin_control
Executing command 'apt-get update'
Ign http://mirrors.liquidweb.com trusty InRelease
Hit http://mirrors.liquidweb.com trusty Release.gpg
Hit http://mirrors.liquidweb.com trusty Release
Hit http://mirrors.liquidweb.com trusty/main amd64 Packages
Ign http://us.archive.ubuntu.com trusty-updates InRelease
Hit http://mirrors.liquidweb.com trusty/universe amd64 Packages
Get:1 http://us.archive.ubuntu.com trusty-updates Release.gpg [933 B]
Hit http://mirrors.liquidweb.com trusty/multiverse amd64 Packages
Hit http://mirrors.liquidweb.com trusty/main Translation-en
Hit http://mirrors.liquidweb.com trusty/multiverse Translation-en
Hit http://mirrors.liquidweb.com trusty/universe Translation-en
Get:2 http://us.archive.ubuntu.com trusty-updates Release [62.0 kB]
Get:3 http://us.archive.ubuntu.com trusty-updates/main amd64 Packages [446 kB]
Get:4 http://us.archive.ubuntu.com trusty-updates/restricted amd64 Packages [8875 B]
Get:5 http://us.archive.ubuntu.com trusty-updates/main Translation-en [213 kB]
Hit http://us.archive.ubuntu.com trusty-updates/restricted Translation-en
```

I've switched which machine is the sync machine and cycled out this machine.
